const MENU_ITEMS = {
  breakfast: [
    {
      id: 1,
      name: "Pohe + Shev",
      price: 25,
      stock: 50,
      desc: "Maharashtrian magic",
      img: "../images/breakfast2.png",
      rating: 4.8,
    },
    {
      id: 2,
      name: "Upma + Shev",
      price: 30,
      stock: 40,
      desc: "Comforting semolina",
      img: "../images/breakfast3.png",
      rating: 4.6,
    },
    {
      id: 11,
      name: "Fruit plate",
      price: 70,
      stock: 40,
      desc: "fresh healthy refreshing",
      img: "../images/fruitplate.jpg",
      rating: 4.9,
    },
    {
      id: 14,
      name: "Vada pav",
      price: 30,
      stock: 40,
      desc: "Bombay famous",
      img: "../images/breakfast1.png",
      rating: 4.6,
    },
    {
      id: 12,
      name: "patis",
      price: 20,
      stock: 40,
      desc: "quick food",
      img: "../images/p.webp",
      rating: 4.4,
    },
  ],
  lunch: [
    {
      id: 3,
      name: "Pav Bhaji",
      price: 120,
      stock: 30,
      desc: "Satisfying food",
      img: "../images/lunch2.png",
      rating: 4.5,
    },
    {
      id: 4,
      name: "Hakka Noodles",
      price: 90,
      stock: 25,
      desc: "Classic stir-fried",
      img: "../images/l3.png",
      rating: 4.4,
    },
    {
      id: 13,
      name: "Khichdi",
      price: 40,
      stock: 40,
      desc: "salty upvas plate",
      img: "../images/lunch1.png",
      rating: 4.4,
    },
    {
      id: 9,
      name: "Appe",
      price: 50,
      stock: 40,
      desc: "south food",
      img: "../images/appe.jpg",
      rating: 4.8,
    },
  ],
  sandwiches: [
    {
      id: 5,
      name: "Veg Club Sandwich",
      price: 95,
      stock: 35,
      desc: "Triple-decker goodness",
      img: "../images/sandwich1.png",
      rating: 4.6,
    },
    {
      id: 6,
      name: "Chocolate Sandwich",
      price: 70,
      stock: 45,
      desc: "Crispy and sweet",
      img: "../images/sandwich2.png",
      rating: 4.7,
    },
  ],
  beverages: [
    {
      id: 7,
      name: "Cold Coffee",
      price: 60,
      stock: 60,
      desc: "Refreshing chill",
      img: "../images/beverage1.png",
      rating: 4.6,
    },
    {
      id: 8,
      name: "Mango Milkshake",
      price: 80,
      stock: 40,
      desc: "Creamy delight",
      img: "../images/beverage2.png",
      rating: 4.8,
    },

    {
      id: 10,
      name: "Fruit juice",
      price: 80,
      stock: 40,
      desc: "fresh healthy delight",
      img: "../images/fruitjuice.jpg",
      rating: 4.6,
    },
  ],
};
